### PR TITLE
implement displaying of registered users

### LINKED ISSUE #95: Add a view for admin to see the registrations data through admins dashboard.
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**
Admin can not see registrations data via website.

**Expected behaviour:**
Admin will be able to see registrations data via website.

### PR DESCRIPTION
**Pull request by danswater**
resolves #95

### CODE REVIEW

**Comment by chaitanyagiri** [comment]
@danswater  what you did was good but actually, we wanted to have a view support in which admin can see the list of all the users(usernames) registered for every particular event and a list of all the events(event Name) that a user has registered for.
You'll need to work with the registrations schema and extract data of users and events from it.

**Comment by danswater** [comment]
@chaitanyagiri I was in the assumption that the requirements was just simply pull the data from the db and display it do the admin, pardon for that.

I'm planning to re-implement it and start on displaying all users registered for every particular event. I'm thinking like this one.

| Users        | Event           |
| ------------- |:-------------:|
| User1     | event1 |
|      | event2      |
|  | event3      |
| User2 | event1 |
| | event2 |

what do you think?

**Comment by chaitanyagiri** [comment]
@danswater that looks fine. It'd be good to have two columns of a user(Name and username) and Event name(s) in front of it. Rest looks good.

**Comment by danswater** [comment]
@chaitanyagiri if you have time can you take a look of this again? Thanks.

**Comment by chaitanyagiri** [comment]
Looks fine to me. @danswater  I think we should merge it later we'll make some changes to adjust CSS but otherwise, it looks good. Thanks for the PR.

**Pull request merged**
