### PR TITLE
Edited the css to make font types all aligned into one font type

### PR DESCRIPTION
**Pull request by ChathuminaVimukthi**

### CODE REVIEW

**Comment by chaitanyagiri** [comment]
Hey, @ChathuminaVimukthi  Can you please add some screenshots depicting your changes?

**Comment by ChathuminaVimukthi** [comment]
screen shot 2017-10-31 at 4 19 32 pm
screen shot 2017-10-31 at 4 19 46 pm
screen shot 2017-10-31 at 4 20 01 pm

**Comment by ChathuminaVimukthi** [comment]
Just let me know if the font type needed to be changed.  :)

**Comment by chaitanyagiri** [comment]
I think poiret-one will look better.

**Comment by ChathuminaVimukthi** [comment]
I will make the changes ASAP..

**Pull request merged**
